version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=amenmansouri_person
      - persist_to_workspace:
         root: ./
         paths:
           - target/

  test:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ./mvnw test
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - test:
          requires:
            - build
